// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "cellar": Application User Types
//
// Command:
// $ goagen
// --design=github.com/hieuphq/goa-example/design
// --out=$(GOPATH)/src/github.com/hieuphq/goa-example
// --version=v1.3.1

package client
